### ISSUE TITLE
Crypt2.munki.recipe is potentially an invalid file

### ISSUE THREAD

**Issue by jby** [autopkg/grahamgilbert-recipes#50]
When testing 2.8.1 with @nmcspadden rewrite I get this error:
WARNING: /Users/jonasb/Library/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes/Crypt2/Crypt2.munki.recipe is potentially an invalid file, not adding it to the recipe map! Please file a GitHub Issue for this repo.
More info here: https://macadmins.slack.com/archives/C056155B4/p1691608955567799

**Comment by jazzace** [comment]
The new AutoPkg 3 flags any recipe without an Input dict present (rightly or wrongly). Since you have already documented that this recipe (and the paired download recipe) was superseded over 2 years ago, deleting the recipe would eliminate the above warning message when running (any) recipes in AutoPkg 3.

**Comment by grahamgilbert** [comment]
I'd take a PR to delete them pretty happily.
